### PR TITLE
Fixing

### LINKED ISSUE #214: Call GSD directly with creating  SD.NMR
https://github.com/cheminfo/nmr-displayer/blob/83e7ea50a88bb1456970772dfd6546bca543f9cf/src/data/data1d/autoPeakPicking.js#L9-L17

You should check not to never make an instance of SD.NMR. It is a waste of time.

For GSD I think you should call it directly from nmr-displayer.

Please also check why the auto peak picking is soo bad. No reason to find peaks in the sloop.

image

### LINKED ISSUE #256: Auto range picking not working well
https://cheminfo.github.io/nmr-displayer/#/admin/ethylvinylether1hjson

Does not find the multiplet on the left

### LINKED ISSUE #429: Autophase correction
Add an algorithm for auto phase correction

### LINKED ISSUE #437: automatic range picking is failing to identify wide enough range
the results is a wrong integral and incorrect multiplicity

### PR DESCRIPTION
**Pull request by jobo322**
In this pull request there are mainly those changes:
- calling nmr-processing for automatic peaks and ranges picking (so, we need first publish this),

- changed default options for automatic ranges picking avoiding big wrong ranges,

- reduced code for  FFT and added phase correction of residual angle [grpdelay - Int(grpdelay)] if the digital filter is applied

- added noiseFactor option to automatic peak picking option panel 

Resolves #429  resolves #437  resolves #256 resolves #214

### CODE REVIEW

File: src/data/data1d/filter1d/autoPhaseCorrection.js [hunk 1]
```diff
@@ -11,13 +11,19 @@ export const name = 'automatic phase correction';
...
+  minRegSize: 30,
+  maxDistanceToJoin: 256,
+};
+
 export function apply(datum1D, options = {}) {
   if (!isApplicable(datum1D)) {
     throw new Error('phaseCorrection not applicable on this data');
   }
-  let { minRegSize = 256 } = options;
+  Object.assign(defaultOptions, options);
```
Comment (lpatiny) [inline src/data/data1d/filter1d/autoPhaseCorrection.js:24]: This is not correct seems to me. I will fix it.

File: src/data/data1d/filter1d/fft.js [hunk 2]
```diff
@@ -13,23 +16,18 @@ export function apply(datum1D) {
...
 
-  let re = new Float64Array(datum1D.data.re);
-  let im = new Float64Array(datum1D.data.im);
+  let digitalFilterApplied = datum1D.filters.some(
+    (e) => e.name === 'digitalFilter' && e.flag,
+  );
 
-  const nbPoints = re.length;
-  FFT.init(nbPoints);
+  Object.assign(datum1D.data, reimFFT(datum1D.data, { applyZeroShift: true }));
```
Comment (lpatiny) [inline src/data/data1d/filter1d/fft.js:23]: Why not using

datum1D.data = reimFFT(datum1D.data, { applyZeroShift: true }

We need to keep the reference to the data property ?

File: src/data/data1d/filter1d/fft.js [hunk 3]
```diff
@@ -13,23 +16,18 @@ export function apply(datum1D) {
...
-  let newRe = new Float64Array(re);
-  let newIm = new Float64Array(im);
-  newRe.set(re.slice(0, (nbPoints + 1) / 2), (nbPoints + 1) / 2);
-  newRe.set(re.slice((nbPoints + 1) / 2));
-  newIm.set(im.slice(0, (nbPoints + 1) / 2), (nbPoints + 1) / 2);
-  newIm.set(im.slice((nbPoints + 1) / 2));
+  if (digitalFilterApplied) {
+    let { digitalFilter } = datum1D.info;
+    let ph1 = (digitalFilter - Math.floor(digitalFilter)) * Math.PI * 2;
+    Object.assign(datum1D.data, reimPhaseCorrection(datum1D.data, 0, ph1));
```
Comment (lpatiny) [inline src/data/data1d/filter1d/fft.js:28]: Same question here

File: src/data/data1d/autoPeakPicking.js [hunk 4]
```diff
@@ -1,25 +1,30 @@
...
+    {
+      noiseLevel: noise * noiseFactor,
+      minMaxRatio: minMaxRatio, // Threshold to determine if a given peak should be considered as a noise
+      realTopDetection: true,
+      maxCriteria: true,
+      smoothY: false,
+      sgOptions: { windowSize: 15, polynomial: 3 },
+    },
+  );
+    console.log('data', peaks.slice());
```
Comment (lpatiny) [inline src/data/data1d/autoPeakPicking.js:23]: Should remove the console logs

File: src/data/data1d/autoRangesDetection.js [hunk 5]
```diff
@@ -13,20 +13,26 @@ export default function autoRangesDetection(datum1D, options) {
...
-    nH,
-    compile,
-    frequencyCluster,
-    clean,
-    keepPeaks,
-    sgOptions: { windowSize: 7, polynomial: 3 },
-  });
 
+  let { frequency, nucleus } = datum1D.info;
+  let { re, x } = datum1D.data;
```
Comment (lpatiny) [inline src/data/data1d/autoRangesDetection.js:18]: Should be const

File: src/data/data1d/filter1d/fft.js (hunk 2 above)
Comment (jobo322) [reply src/data/data1d/filter1d/fft.js:23]: because reimFFT return { re, im } and data has x, re, im properties
